module.exports = Router.extend(
  routes:
    '': 'home'
    'users/:id': 'userDetail'
    'info': 'info'
  home: ->
    @trigger 'newPage', new HomePage
    return
  userDetail: (id) ->
    user = app.users.get(id)
    if user
      @trigger 'newPage', new HomePage
    else
      @redirectTo 'users'
    return
)

# ---
# generated by js2coffee 2.1.0
